// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SapApi.Infrastructure.Persistence;

#nullable disable

namespace SapApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811135802_AddIssueForProductionRequestListFields")]
    partial class AddIssueForProductionRequestListFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApprovalPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("RequesterGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("RequesterType")
                        .HasColumnType("integer");

                    b.Property<int?>("RequesterUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterGroupId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("CompanyDb", "DocumentType");

                    b.ToTable("ApprovalPolicies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("CompanyDb", "ApprovalRequestId");

                    b.ToTable("ApprovalLogs");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalPolicyApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalPolicyId")
                        .HasColumnType("integer");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalPolicyId");

                    b.HasIndex("ApproverUserId");

                    b.ToTable("ApprovalPolicyApprovers");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalPolicyRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalPolicyId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalPolicyId");

                    b.ToTable("ApprovalPolicyRules");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OverallStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyId")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("integer");

                    b.Property<string>("SapResponseDocEntry")
                        .HasColumnType("text");

                    b.Property<string>("SapResponseDocNum")
                        .HasColumnType("text");

                    b.Property<string>("SupportingData")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("CompanyDb", "OverallStatus");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.CacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("CompressedValue")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Key");

                    b.HasIndex("CompanyDb", "ExpiresAtUtc");

                    b.ToTable("CacheEntries");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.IssueForProductionRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDb");

                    b.ToTable("IssueForProductionRequests");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BPLId")
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CardName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ContactPersonCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocCurrency")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DocDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<int?>("DocNum")
                        .HasColumnType("integer");

                    b.Property<double?>("DocRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("DocTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("DocType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DocumentStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("DocumentsOwner")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JournalMemo")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumAtCard")
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("RoundingDiffAmount")
                        .HasColumnType("double precision");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("integer");

                    b.Property<string>("ShipToCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TaxDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TotalDiscount")
                        .HasColumnType("double precision");

                    b.Property<int?>("TransportationCode")
                        .HasColumnType("integer");

                    b.Property<string>("UContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("UDelTerms")
                        .HasColumnType("text");

                    b.Property<string>("UDisId")
                        .HasColumnType("text");

                    b.Property<string>("UDispachAdd")
                        .HasColumnType("text");

                    b.Property<string>("UDispatchTo")
                        .HasColumnType("text");

                    b.Property<string>("UDrawDocs")
                        .HasColumnType("text");

                    b.Property<string>("UGoodsIssue")
                        .HasColumnType("text");

                    b.Property<string>("UGoodsReceipt")
                        .HasColumnType("text");

                    b.Property<string>("UInspectionBy")
                        .HasColumnType("text");

                    b.Property<string>("ULoading")
                        .HasColumnType("text");

                    b.Property<string>("UMatInDoc")
                        .HasColumnType("text");

                    b.Property<string>("UMatOutDoc")
                        .HasColumnType("text");

                    b.Property<string>("UModeOfTransport")
                        .HasColumnType("text");

                    b.Property<string>("UOtherRemark")
                        .HasColumnType("text");

                    b.Property<string>("UOwner")
                        .HasColumnType("text");

                    b.Property<string>("UPainting")
                        .HasColumnType("text");

                    b.Property<string>("UPoType")
                        .HasColumnType("text");

                    b.Property<string>("UPriceBasis")
                        .HasColumnType("text");

                    b.Property<string>("URemark")
                        .HasColumnType("text");

                    b.Property<string>("UStage")
                        .HasColumnType("text");

                    b.Property<string>("USupervision")
                        .HasColumnType("text");

                    b.Property<string>("UTestCerts")
                        .HasColumnType("text");

                    b.Property<string>("UTransitIns")
                        .HasColumnType("text");

                    b.Property<string>("UTransportation")
                        .HasColumnType("text");

                    b.Property<string>("UTrn")
                        .HasColumnType("text");

                    b.Property<string>("UUnloading")
                        .HasColumnType("text");

                    b.Property<string>("UWarehouse")
                        .HasColumnType("text");

                    b.Property<string>("UWarranty")
                        .HasColumnType("text");

                    b.Property<double?>("VatSum")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDb", "CardCode");

                    b.HasIndex("CompanyDb", "DocDate");

                    b.HasIndex("CompanyDb", "DocEntry")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CompanyDb", "DocNum");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .HasColumnType("text");

                    b.Property<int?>("BaseEntry")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseLine")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseType")
                        .HasColumnType("integer");

                    b.Property<string>("CostingCode")
                        .HasColumnType("text");

                    b.Property<string>("CostingCode2")
                        .HasColumnType("text");

                    b.Property<string>("CostingCode3")
                        .HasColumnType("text");

                    b.Property<string>("CostingCode4")
                        .HasColumnType("text");

                    b.Property<string>("CostingCode5")
                        .HasColumnType("text");

                    b.Property<double?>("DiscountPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("GrossTotal")
                        .HasColumnType("double precision");

                    b.Property<int?>("HSNEntry")
                        .HasColumnType("integer");

                    b.Property<double?>("InventoryQuantity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<double?>("LineTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("text");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int?>("SACEntry")
                        .HasColumnType("integer");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text");

                    b.Property<string>("TaxLiable")
                        .HasColumnType("text");

                    b.Property<double?>("TaxPercentagePerRow")
                        .HasColumnType("double precision");

                    b.Property<double?>("TaxTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("UProdNo")
                        .HasColumnType("text");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("UnitsOfMeasurment")
                        .HasColumnType("double precision");

                    b.Property<string>("UoMCode")
                        .HasColumnType("text");

                    b.Property<int?>("UoMEntry")
                        .HasColumnType("integer");

                    b.Property<string>("UseBaseUnits")
                        .HasColumnType("text");

                    b.Property<string>("WTLiable")
                        .HasColumnType("text");

                    b.Property<string>("WarehouseCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId", "LineNum")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrderPaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Basic")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Gst")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId", "Slot")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("PurchaseOrderPaymentTerms");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrderSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("LastDocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("LastSyncMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastSyncedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDb")
                        .IsUnique();

                    b.ToTable("PurchaseOrderSyncStates");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ReceiptFromProductionRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDb");

                    b.ToTable("ReceiptFromProductionRequests");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApDownPaymentInvoiceEntryNumber")
                        .HasColumnType("text");

                    b.Property<string>("ApInvoiceDocEntry")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalRequestId")
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .HasColumnType("text");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DownPaymentDocEntry")
                        .HasColumnType("text");

                    b.Property<double?>("GrossAmount")
                        .HasColumnType("double precision");

                    b.Property<double?>("GstAmount")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentDocEntry")
                        .HasColumnType("text");

                    b.Property<int?>("PaymentTermsType")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("StageDesc")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("Tds")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UtrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UtrNo")
                        .HasColumnType("text");

                    b.Property<string>("WtCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("CompanyDb", "DocNumber");

                    b.ToTable("StageWisePayments");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalRequestId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("DownPaymentStageWisePaymentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JournalRemark")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeOfPayment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PoDocEntry")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.Property<int?>("StageWisePaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WtCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("DownPaymentStageWisePaymentId")
                        .IsUnique();

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("StageWisePaymentId")
                        .IsUnique();

                    b.HasIndex("CompanyDb", "PoDocEntry");

                    b.ToTable("StageWisePaymentBatches");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatchLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("ApInvoiceDocEntry")
                        .HasColumnType("text");

                    b.Property<double?>("BalanceDue")
                        .HasColumnType("double precision");

                    b.Property<string>("Bank")
                        .HasColumnType("text");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LineOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("Payable")
                        .HasColumnType("double precision");

                    b.Property<string>("WtCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("StageWisePaymentBatchLines");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatchLinePaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LineId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentTermDesc")
                        .HasColumnType("text");

                    b.Property<int>("PaymentTermsType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LineId", "PaymentTermsType")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StageWisePaymentBatchLinePaymentTerms");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.UserApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserApprovals");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyDb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDb", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.UserGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserGroupId", "UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("UserGroupMembers");
                });

            modelBuilder.Entity("ApprovalPolicy", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.UserGroup", "RequesterGroup")
                        .WithMany()
                        .HasForeignKey("RequesterGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", "RequesterUser")
                        .WithMany("Policy")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequesterGroup");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalLog", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapApi.Domain.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany()
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("ApprovalRequest");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalPolicyApprover", b =>
                {
                    b.HasOne("ApprovalPolicy", "Policy")
                        .WithMany("Approvers")
                        .HasForeignKey("ApprovalPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", "ApproverUser")
                        .WithMany("PolicyApprover")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalPolicyRule", b =>
                {
                    b.HasOne("ApprovalPolicy", "Policy")
                        .WithMany("Rules")
                        .HasForeignKey("ApprovalPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("ApprovalPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapApi.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", "RequesterUser")
                        .WithMany("ApprovalRequest")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrderPaymentTerm", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PaymentTerms")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePayment", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("StageWisePayments")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatch", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.StageWisePayment", "DownPaymentStageWisePayment")
                        .WithOne()
                        .HasForeignKey("SapApi.Domain.Entities.StageWisePaymentBatch", "DownPaymentStageWisePaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SapApi.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("StageWisePaymentBatches")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SapApi.Domain.Entities.StageWisePayment", "StageWisePayment")
                        .WithOne()
                        .HasForeignKey("SapApi.Domain.Entities.StageWisePaymentBatch", "StageWisePaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DownPaymentStageWisePayment");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("StageWisePayment");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatchLine", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.StageWisePaymentBatch", "Batch")
                        .WithMany("Lines")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatchLinePaymentTerm", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.StageWisePaymentBatchLine", "Line")
                        .WithMany("PaymentTerms")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.UserApproval", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany("UserApprovals")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.UserGroupMember", b =>
                {
                    b.HasOne("SapApi.Domain.Entities.UserGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapApi.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApprovalPolicy", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ApprovalRequest");

                    b.Navigation("Policy");

                    b.Navigation("PolicyApprover");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Navigation("UserApprovals");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("Lines");

                    b.Navigation("PaymentTerms");

                    b.Navigation("StageWisePaymentBatches");

                    b.Navigation("StageWisePayments");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatch", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.StageWisePaymentBatchLine", b =>
                {
                    b.Navigation("PaymentTerms");
                });

            modelBuilder.Entity("SapApi.Domain.Entities.UserGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
